<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CONTACT_TEXT_ALL' => 'Пожалуйста, если у Вас есть чем поделиться, свяжитесь со мной',
    'CONTACT_ALL_REQUIRED' => 'Пожалуйста, заполните все поля',
    'CONTACT_BUTTON_SEND' => 'Отправить',
    'CONTACT_EMAIL' => 'Е-маил',
    'CONTACT_EMAIL_CORRECT' => 'Пожалуйста, введите правильный е-маил',
    'CONTACT_ERROR_SEND' => 'Ошибка при отправке',
    'CONTACT_SUBJECT' => 'Тема',
    'CONTACT_SUCCESS_SEND' => 'Спасибо за Ваше сообщение',
    'CONTACT_TEXT' => 'Сообщение',
    'CONTACT_USERNAME' => 'Имя',
    'EMAIL_NOT_CORRECT' => 'Введите пожалуйста, правильный е-маил',
    'EMAIL_NOT_IN_BASE' => 'Данный адрес не существует в базе',
    'EMAIL_REQUIRED' => 'Пожалуйста, заполните Ваш электронный адрес',
    'ENETER_NEW_PASSWORD' => 'Пожалуйста, введите новый пароль',
    'ENTER_NEW_PASSWORD' => 'Пожалуйста, введите новый пароль',
    'ERROR_SEND_EMAIL' => 'Ошибка при отправке е-маила',
    'LOGIN_ENTER_LOGIN_PASSWORD' => 'Пожалуйста, введите Ваш логин и пароль',
    'LOGIN_LINK_RESETPASSWORD' => 'восстановить пароль',
    'LOGIN_SUBMIT' => 'Вход',
    'LOGIN_TEXT_IFFORGETPASSWORD' => 'Если Вы забыли пароль, то Вы можете',
    'NAV_ABOUT' => 'Обо мне',
    'NAV_CONTACT' => 'Контакт',
    'NAV_HOME' => 'Главная',
    'NAV_LOGIN' => 'Вход',
    'NAV_LOGOUT' => 'Выход',
    'NEW_PASSWORD_SAVE' => 'Новый пароль сохранен в системе',
    'PAGE_DONT_EXIST' => 'Извините, но такой страницы не существует',
    'PASSWORD_TOKEN_CAN_BELANK' => 'Неверный ключ',
    'REQUEST_PASSWORD_RESET_TOKEN' => 'Восстановление пароля',
    'REQUEST_SUBMIT' => 'Восстановить',
    'REQUETS_TOKEN_TEXT' => 'Пожалуйста, укажите Ваш email',
    'RESET_PASSWORD' => 'Пожалуйста, укажите Ваш е-маил',
    'RESET_PASSWORD_CHECK_MAIL_INSTRUCTIONS' => 'Инструкции по восстановлению пароля отправлены Вам на электронную почту',
    'SUBMIT_BUTTON' => 'Отправить',
    'USER_PASSWORD' => 'Пароль',
    'USER_PASSWORD_REQUIRED' => 'Пожалуйста, введите Ваш пароль',
    'USER_REMEMBER_ME' => 'Запомнить меня',
    'USER_USERNAME' => 'Логин',
    'USER_USERNAME_INCORRECT_OR_PASSWORD' => 'Вы указали неверный логин или пароль',
    'USER_USERNAME_REQUIRED' => 'Пожалуйста, введите Ваш логин',
    'WRONG_PASSWORD_TOKEN' => 'Ошибка при инициализации токена',
];
