<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "posts".
 *
 * @property integer $id
 * @property string $img_post
 * @property string $title
 * @property string $small_description
 * @property string $Description
 * @property string $date
 */
class Posts extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
public $file;

    public static function tableName()
    {
        return 'posts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'title', 'small_description', 'Description'], 'required'],
            [['small_description', 'Description'], 'string'],
            [['date'], 'safe'],
            [['file'], 'file'],
            [['img_post'], 'string', 'max' => 255],
            [['title'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file' => 'Img Post',
            'title' => 'Title',
            'small_description' => 'Small Description',
            'Description' => 'Description',
            'date' => 'Date',
        ];
    }

  public function beforeDelete()
  {
      if ($this->img_post) {
        // var_dump('../../frontend/web/' . $this->img_post);
          //exit('=e');
          unlink( '../../frontend/web/' . $this->img_post);

      }

      return parent::beforeDelete(); // TODO: Change the autogenerated stub
  }


}
