<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CONTACT_EMAIL' => '',
    'CONTACT_SUBJECT' => '',
    'CONTACT_TEXT' => '',
    'CONTACT_TEXT_ALL' => '',
    'CONTACT_USERNAME' => '',
    'POST_DATE' => '',
    'POST_DESCTIPTION' => '',
    'POST_ID' => '',
    'POST_SMALL_DESCTIPTION' => '',
    'POST_TITLE' => '',
    'CONTACT_ALL_REQUIRED' => 'Please enter the fields',
    'CONTACT_BUTTON_SEND' => 'Send',
    'CONTACT_EMAIL_CORRECT' => 'Email is correct',
    'CONTACT_ERROR_SEND' => 'Error to send contact',
    'CONTACT_SUCCESS_SEND' => 'Thank for contact',
    'EMAIL_NOT_CORRECT' => 'Incorrect email',
    'EMAIL_NOT_IN_BASE' => 'Email not in base',
    'EMAIL_REQUIRED' => 'Please, enter your email',
    'ENETER_NEW_PASSWORD' => 'Please, enter new password',
    'ENTER_NEW_PASSWORD' => 'Enter new password',
    'ERROR_SEND_EMAIL' => 'Error send email',
    'LOGIN_ENTER_LOGIN_PASSWORD' => 'Enter your login and password',
    'LOGIN_LINK_RESETPASSWORD' => 'reset password',
    'LOGIN_SUBMIT' => 'Enter',
    'LOGIN_TEXT_IFFORGETPASSWORD' => 'If you forget your password, you can',
    'NAV_ABOUT' => 'About',
    'NAV_CONTACT' => 'Contact',
    'NAV_HOME' => 'Home',
    'NAV_LOGIN' => 'Login',
    'NAV_LOGOUT' => 'Logout',
    'NEW_PASSWORD_SAVE' => 'Passwod save',
    'PAGE_DONT_EXIST' => 'Page does not exist',
    'PASSWORD_TOKEN_CAN_BELANK' => 'Password token cannot be blank',
    'REQUEST_PASSWORD_RESET_TOKEN' => 'Please, enter your email',
    'REQUEST_SUBMIT' => 'Send',
    'REQUETS_TOKEN_TEXT' => 'Please, enter your email',
    'RESET_PASSWORD' => 'New password',
    'RESET_PASSWORD_CHECK_MAIL_INSTRUCTIONS' => 'Reset password was success. Please, check your email',
    'SUBMIT_BUTTON' => 'Reset',
    'USER_PASSWORD' => 'Password',
    'USER_PASSWORD_REQUIRED' => 'Please, enter your passowd',
    'USER_REMEMBER_ME' => 'Remember me',
    'USER_USERNAME' => 'Login',
    'USER_USERNAME_INCORRECT_OR_PASSWORD' => 'Username or password does not exist',
    'USER_USERNAME_REQUIRED' => 'Please, enter your login',
    'WRONG_PASSWORD_TOKEN' => 'Wrong password token',
];
